### ISSUE TITLE
[BUG] DB cache file not created

### ISSUE THREAD

**Issue by marcogiorgio** [linuxserver/docker-feed2toot#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The db file cache specified in feed2toot.ini is not created 

### Expected Behavior

The db file cache specified in feed2toot.is created 

### Steps To Reproduce

Deploy the image using this compose file:
<details>
 <summary>docker-compose.yml</summary>

```yaml
version: "2.1"
services:
  feed2toot:
    image: lscr.io/linuxserver/feed2toot:latest
    container_name: feed2toot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
```
</details>

Confirm that feed2toot.ini is configured to use a cache file:
<details>
  <summary>feed2toot.ini</summary>
 
  ```
[mastodon]
instance_url=https://mastodon.URL.com
user_credentials=/config/feed2toot_usercred.txt
client_credentials=/config/feed2toot_clientcred.txt
toot_visibility=private

[cache]
cachefile=/config/feed2toot.db
cache_limit=100

[rss]
uri_list=/config/urilist.txt                                                                                            toot={title} {link} \n \n {summary:.200}

[lock]
lock_file=/config/feed2toot.lock

[hashtaglist]
several_words_hashtags_list=/config/hashtags.txt  
  ```
  
</details>

After the creation of the container and the first rss to mastodon sync, a .lock file is created inside the config folder, but not a  .db

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker compose up -d
```

### Container logs

```bash
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
feed2toot: https://liberapay.com/carlchenet/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
